version: '1.0'
services:
  - type: web
    name: nexuscoders-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: MONGODB_URI
        sync: false
      - key: SESSION_DATA
        sync: false

  - type: worker
    name: nexuscoders-whatsapp-bot-worker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 14
      - key: MONGODB_URI
        sync: false
      - key: SESSION_DATA
        sync: false

static_sites:
  - name: nexuscoders-whatsapp-bot-static
    env: static
    buildCommand: npm run build
    staticPublishPath: ./public
    routes:
      - path: /*

databases:
  - name: nexuscoders-whatsapp-bot-db
    databaseName: nexuscoders
    user: nexuscoders

addons:
  - plan: mongodb-addon
    as: MONGODB
